### ISSUE TITLE
Do freeruns have value? and bowlo if so

### ISSUE THREAD

**Issue by horrible-little-slime** [loathers/chrono-collector#31]

**Comment by docrostov** [comment]
yep, they do. you can use freeruns to burn delay on the scheduled NC in the first floor, from which you get twitching time capsules, from which you get solid shifting time weirdness. we should be putting wanderers in the globe stage, as we currently are, since wanderers also drop roses/tulips... but freeruns should probably be used on the first floor in search of more capsules.

**Comment by horrible-little-slime** [comment]
I can add asdonbumper and bowling ball for this; does mafia have explicit tracking for it, or is it just turnsSpent?
